-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_ID, PRODUCT.PRODUCT_NAME, SUM(PRODUCT.PRICE * FORDER.AMOUNT) AS TOTAL_SALES 
FROM FOOD_PRODUCT AS PRODUCT INNER JOIN FOOD_ORDER AS FORDER ON PRODUCT.PRODUCT_ID = FORDER.PRODUCT_ID 
WHERE FORDER.PRODUCE_DATE LIKE "2022-05%" GROUP BY PRODUCT.PRODUCT_ID ORDER BY SUM(PRODUCT.PRICE * FORDER.AMOUNT) DESC, PRODUCT.PRODUCT_ID