-- 코드를 입력하세요
SELECT APNT.APNT_NO, PT.PT_NAME, APNT.PT_NO, APNT.MCDP_CD, DR.DR_NAME, APNT.APNT_YMD
FROM PATIENT AS PT INNER JOIN APPOINTMENT AS APNT ON PT.PT_NO = APNT.PT_NO
INNER JOIN DOCTOR AS DR ON DR.DR_ID = APNT.MDDR_ID
WHERE APNT.APNT_YMD LIKE "2022-04-13%" AND APNT.APNT_CNCL_YN = "N"
ORDER BY APNT_YMD