-- 코드를 입력하세요
SELECT DISTINCT RENTAL.CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR AS RENTAL INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY ON RENTAL.CAR_ID = HISTORY.CAR_ID
WHERE RENTAL.CAR_TYPE = "세단" AND START_DATE LIKE "%-10-%" ORDER BY RENTAL.CAR_ID DESC;